---
concurrency:
  cancel-in-progress: false
  group: pages
jobs:
  pages:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1
        with:
          fetch-depth: 0
          persist-credentials: false
      - name: Setup Pages
        uses: actions/configure-pages@45bfe0192ca1faeb007ade9deae92b16b8254a0d
      - name: Install dependencies
        run: yarn
      - name: Build documentation
        run: yarn typedoc
      - name: Upload artifact
        uses: actions/upload-pages-artifact@fc324d3547104276b827a68afc52ff2a11cc49c9
        with:
          path: ${{github.workspace}}/docs
      - id: deployment
        name: Deploy to GitHub Pages
        uses: actions/deploy-pages@368f82528645a54fb793d4d04e342629a3f51346
name: GitHub Pages
'on':
  push:
    branches: [master]
permissions:
  contents: read
  id-token: write
  pages: write
