---
concurrency:
  cancel-in-progress: false
  group: pages
jobs:
  pages:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0
      - name: Setup Pages
        uses: actions/configure-pages@v5
      - name: Install dependencies
        run: yarn
      - name: Build documentation
        run: yarn typedoc
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v4
        with:
          path: ${{github.workspace}}/docs
      - id: deployment
        name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
name: GitHub Pages
'on':
  push:
    branches: [master]
permissions:
  contents: read
  id-token: write
  pages: write
