jobs:
  qa:
    runs-on: 'ubuntu-latest'
    steps:
      - uses: 'actions/checkout@v5'
      - name: 'Install dependencies (Yarn)'
        run: 'yarn'
      - name: 'ESLint'
        run: 'yarn eslint'
      - name: 'Check formatting'
        run: 'yarn check-formatting'
      - name: 'Check spelling'
        run: 'yarn check-spelling'
name: 'QA'
'on':
  pull_request:
    branches:
      - 'master'
  push:
    branches:
      - 'master'
permissions:
  contents: 'read'
